<?php

return [
    'groups' => [
        'transactions' => 'العمليات المالية',
        'customers' => 'العملاء',
        'boxes' => 'الصناديق الجديدة',
        'vaults' => 'الصناديق',
        'currencies' => 'العملات وأسعار الصرف',
        'dashboard' => 'لوحة التحكم',
        'reconciliation' => 'المطابقة المالية',
        'reports' => 'التقارير',
        'users' => 'المستخدمون',
        'settings' => 'الإعدادات',
        'archive' => 'الأرشيف',
        'notifications' => 'الإشعارات',
    ],

    'roles' => [
        'owner' => 'مالك',
        'admin' => 'مدير عام',
        'manager' => 'مدير',
        'operations_employee' => 'موظف عمليات',
    ],

    'system_roles' => [
        'owner',
        'admin',
        'manager',
        'operations_employee',
    ],

    'critical_owner_permissions' => [
        'transaction.viewAny',
        'transaction.view',
        'transaction.create',
        'transaction.update',
        'transaction.delete',
        'transaction.restore',
        'transaction.forceDelete',
        'transaction.export',
        'customer.viewAny',
        'customer.view',
        'customer.create',
        'customer.update',
        'customer.delete',
        'customer.restore',
        'customer.forceDelete',
        'customer.viewBalance',
        'customer.viewStatement',
        'box.viewAny',
        'box.view',
        'box.create',
        'box.update',
        'box.delete',
        'box.adjustBalance',
        'box.viewLogs',
        'box.adjustment.view',
        'box.adjustment.create',
        'vault.viewAny',
        'vault.view',
        'vault.update',
        'currency.viewAny',
        'currency.manage',
        'exchange_rate.update',
        'dashboard.viewFinancial',
        'reconciliation.view',
        'reconciliation.run',
        'report.daily',
        'report.monthly',
        'report.export',
        'report.viewAll',
        'user.viewAny',
        'user.view',
        'user.create',
        'user.update',
        'user.delete',
        'user.setVaultBalance',
        'settings.view',
        'settings.manage',
        'archive.view',
        'archive.restore',
        'notification.viewAny',
        'notification.read',
        'notification.delete',
    ],

    'permissions' => [
        'transaction.viewAny' => ['label' => 'عرض كل العمليات المالية', 'group' => 'transactions'],
        'transaction.view' => ['label' => 'عرض عملية مالية', 'group' => 'transactions'],
        'transaction.create' => ['label' => 'إنشاء عملية مالية', 'group' => 'transactions'],
        'transaction.update' => ['label' => 'تعديل عملية مالية', 'group' => 'transactions'],
        'transaction.delete' => ['label' => 'حذف عملية مالية', 'group' => 'transactions'],
        'transaction.restore' => ['label' => 'استعادة عملية مالية', 'group' => 'transactions'],
        'transaction.forceDelete' => ['label' => 'حذف عملية مالية نهائياً', 'group' => 'transactions'],
        'transaction.export' => ['label' => 'تصدير العمليات المالية', 'group' => 'transactions'],

        'customer.viewAny' => ['label' => 'عرض كل العملاء', 'group' => 'customers'],
        'customer.view' => ['label' => 'عرض عميل', 'group' => 'customers'],
        'customer.create' => ['label' => 'إنشاء عميل', 'group' => 'customers'],
        'customer.update' => ['label' => 'تعديل عميل', 'group' => 'customers'],
        'customer.delete' => ['label' => 'حذف عميل', 'group' => 'customers'],
        'customer.restore' => ['label' => 'استعادة عميل', 'group' => 'customers'],
        'customer.forceDelete' => ['label' => 'حذف عميل نهائياً', 'group' => 'customers'],
        'customer.viewBalance' => ['label' => 'عرض رصيد العميل', 'group' => 'customers'],
        'customer.viewStatement' => ['label' => 'عرض كشف حساب العميل', 'group' => 'customers'],

        'box.viewAny' => ['label' => 'عرض كل الصناديق الجديدة', 'group' => 'boxes'],
        'box.view' => ['label' => 'عرض صندوق جديد', 'group' => 'boxes'],
        'box.create' => ['label' => 'إنشاء صندوق جديد', 'group' => 'boxes'],
        'box.update' => ['label' => 'تعديل صندوق جديد', 'group' => 'boxes'],
        'box.delete' => ['label' => 'حذف صندوق جديد', 'group' => 'boxes'],
        'box.adjustBalance' => ['label' => 'تعديل رصيد صندوق جديد', 'group' => 'boxes'],
        'box.viewLogs' => ['label' => 'عرض سجل رصيد صندوق جديد', 'group' => 'boxes'],
        'box.adjustment.view' => ['label' => 'عرض تعديلات رصيد الصندوق', 'group' => 'boxes'],
        'box.adjustment.create' => ['label' => 'إنشاء تعديل رصيد الصندوق', 'group' => 'boxes'],

        'vault.viewAny' => ['label' => 'عرض كل الصناديق', 'group' => 'vaults'],
        'vault.view' => ['label' => 'عرض صندوق', 'group' => 'vaults'],
        'vault.update' => ['label' => 'تعديل صندوق', 'group' => 'vaults'],

        'currency.viewAny' => ['label' => 'عرض العملات', 'group' => 'currencies'],
        'currency.manage' => ['label' => 'إدارة العملات', 'group' => 'currencies'],
        'exchange_rate.update' => ['label' => 'تحديث أسعار الصرف', 'group' => 'currencies'],

        'dashboard.viewFinancial' => ['label' => 'عرض لوحة التحكم المالية', 'group' => 'dashboard'],

        'reconciliation.view' => ['label' => 'عرض المطابقة المالية', 'group' => 'reconciliation'],
        'reconciliation.run' => ['label' => 'تنفيذ المطابقة المالية', 'group' => 'reconciliation'],

        'report.daily' => ['label' => 'عرض التقرير اليومي', 'group' => 'reports'],
        'report.monthly' => ['label' => 'عرض التقرير الشهري', 'group' => 'reports'],
        'report.export' => ['label' => 'تصدير التقارير', 'group' => 'reports'],
        'report.viewAll' => ['label' => 'عرض تقارير كل المستخدمين', 'group' => 'reports'],

        'user.viewAny' => ['label' => 'عرض كل المستخدمين', 'group' => 'users'],
        'user.view' => ['label' => 'عرض مستخدم', 'group' => 'users'],
        'user.create' => ['label' => 'إنشاء مستخدم', 'group' => 'users'],
        'user.update' => ['label' => 'تعديل مستخدم', 'group' => 'users'],
        'user.delete' => ['label' => 'حذف مستخدم', 'group' => 'users'],
        'user.setVaultBalance' => ['label' => 'تعديل رصيد صندوق المستخدم', 'group' => 'users'],

        'settings.view' => ['label' => 'عرض الإعدادات', 'group' => 'settings'],
        'settings.manage' => ['label' => 'إدارة الإعدادات', 'group' => 'settings'],

        'archive.view' => ['label' => 'عرض الأرشيف', 'group' => 'archive'],
        'archive.restore' => ['label' => 'استعادة من الأرشيف', 'group' => 'archive'],

        'notification.viewAny' => ['label' => 'عرض الإشعارات', 'group' => 'notifications'],
        'notification.read' => ['label' => 'تعليم الإشعارات كمقروءة', 'group' => 'notifications'],
        'notification.delete' => ['label' => 'حذف الإشعارات', 'group' => 'notifications'],
    ],
];
